spring:
    application:
        name: report-generator

    datasource:
        url: jdbc:postgresql://localhost:5433/your_db_name
        username: your_username
        password: your_password
        driver-class-name: org.postgresql.Driver

filePath:
    report: "report/data.xlsx"

batch:
    size: 1000

threads:
    count: 2